# Generated by Django 3.2.5 on 2021-07-22 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=90)),
                ('name_en', models.CharField(default=None, max_length=90)),
                ('show_order', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=600, null=True)),
                ('icon', models.CharField(default='lightbulb', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(default=None, max_length=90)),
                ('language_cn', models.CharField(default=None, max_length=90)),
                ('name_en', models.CharField(default=None, max_length=90)),
                ('language_en', models.CharField(default=None, max_length=90)),
                ('comment', models.CharField(max_length=600, null=True)),
                ('_flag', models.TextField(blank=True, db_column='flag')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_keyword', models.CharField(max_length=90, unique=True)),
                ('english_keyword', models.CharField(max_length=90, unique=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('similar_set', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=600, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('review_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Subbusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=90)),
                ('name_en', models.CharField(max_length=90)),
                ('show_order', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=600, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teng.business')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=200, unique=True)),
                ('name_en', models.CharField(blank=True, default=None, max_length=200, unique=True)),
                ('credit', models.DecimalField(decimal_places=2, default=7.0, max_digits=3)),
                ('status', models.SmallIntegerField(default=0)),
                ('website', models.CharField(blank=True, default='http://www.baidu.com', max_length=2048)),
                ('scale', models.CharField(default=None, max_length=30)),
                ('built_year', models.SmallIntegerField(default=1970)),
                ('address_cn', models.CharField(blank=True, default='广南路', max_length=300)),
                ('address_en', models.CharField(blank=True, default='广南路', max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_phone', models.CharField(blank=True, default='16621360442', max_length=24)),
                ('cell_phone', models.CharField(blank=True, default='16621360442', max_length=24)),
                ('description_cn', models.CharField(blank=True, default='很不错的公司', max_length=1500)),
                ('description_en', models.CharField(blank=True, default='nice company', max_length=1500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(default='test data', max_length=600, null=True)),
                ('categories', models.ManyToManyField(to='teng.Subbusiness')),
                ('country', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='teng.country')),
                ('products', models.ManyToManyField(to='teng.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_website_turkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.IntegerField(default=0, null=True)),
                ('chinese_keyword', models.CharField(max_length=90, null=True)),
                ('turkish_keyword', models.CharField(max_length=150)),
                ('url_id', models.IntegerField(default=100, null=True)),
                ('status', models.SmallIntegerField(default=0, null=True)),
                ('comment', models.CharField(max_length=600, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('review_time', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='teng.country')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(default=100)),
                ('chinese_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teng.keyword')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teng.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_keyword', models.CharField(max_length=90, unique=True)),
                ('comment', models.CharField(max_length=600, null=True)),
                ('keyword', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='teng.keyword')),
                ('subbusiness', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teng.subbusiness')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_cn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_keyword', models.CharField(max_length=90, unique=True)),
                ('comment', models.CharField(max_length=600, null=True)),
                ('keyword', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='teng.keyword')),
                ('subbusiness', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teng.subbusiness')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='subbusiness',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='teng.subbusiness'),
        ),
    ]
